services:
  - type: web
    name: gameshelf-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        scope: all
        value: mongodb+srv://gameshelfuser:Gameshelf123@cluster0.batkwbj.mongodb.net/?appName=Cluster0
      - key: JWT_SECRET
        scope: all
        value: tu_secreto_jwt_super_seguro_cambiar_en_produccion
      - key: NODE_ENV
        scope: all
        value: production
      - key: PORT
        scope: all
        value: 10000
      - key: RAWG_API_KEY
        scope: all
        value: 62aa1bfcb3464797b03f36c9f8706351
      - key: CORS_ORIGIN
        scope: all
        value: https://gameshelf.vercel.app
